theme: jekyll-theme-cayman
title: Scott
description: Structure Canonisation using Ordered-Tree Translation
logo: https://raw.githubusercontent.com/theplatypus/test-pages/master/docs/scott2.png
show_downloads: "true" 
